export const restaurantImages: Record<string, any[]> = {
  "三雅": [
    require('../assets/images/Chayi_turkey_rice_restarunt/三雅/IMG_8378.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/三雅/IMG_9058.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/三雅/IMG_9059.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/三雅/IMG_9066.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/三雅/IMG_9067.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/三雅/IMG_9453.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/三雅/IMG_9454.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/三雅/IMG_9455.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/三雅/IMG_9456.jpg'),
  ],
  "呆獅": [
    require('../assets/images/Chayi_turkey_rice_restarunt/呆獅/IMG_9483.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/呆獅/IMG_9484.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/呆獅/IMG_9485.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/呆獅/IMG_9486.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/呆獅/IMG_9487.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/呆獅/IMG_9488.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/呆獅/IMG_9489.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/呆獅/IMG_9490.jpg'),
  ],
  "和平火雞肉飯": [
    require('../assets/images/Chayi_turkey_rice_restarunt/和平火雞肉飯/IMG_8437.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/和平火雞肉飯/IMG_8438.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/和平火雞肉飯/IMG_8439.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/和平火雞肉飯/IMG_8440.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/和平火雞肉飯/IMG_8441.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/和平火雞肉飯/IMG_8442.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/和平火雞肉飯/IMG_8443.jpg'),
  ],
  "嘉義人": [
    require('../assets/images/Chayi_turkey_rice_restarunt/嘉義人/IMG_7640.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/嘉義人/IMG_7641.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/嘉義人/IMG_7642.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/嘉義人/IMG_7643.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/嘉義人/IMG_7644.jpg'),
  ],
  "噴水-圓環（中山）": [
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-圓環（中山）/IMG_8379.jpg'),
  ],
  "噴水-小雅": [
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-小雅/IMG_8684.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-小雅/IMG_8950.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-小雅/IMG_8951.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-小雅/IMG_8952.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-小雅/IMG_8953.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-小雅/IMG_8954.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-小雅/IMG_8955.jpg'),
  ],
  "噴水-新民": [
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-新民/IMG_9010.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-新民/IMG_9011.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-新民/IMG_9012.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-新民/IMG_9071.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-新民/IMG_9072.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-新民/IMG_9078.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/噴水-新民/IMG_9081.jpg'),
  ],
  "大同": [
    require('../assets/images/Chayi_turkey_rice_restarunt/大同/IMG_7664.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/大同/IMG_7665.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/大同/IMG_7666.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/大同/IMG_7667.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/大同/IMG_7668.jpg'),
  ],
  "夯仔內火雞肉飯": [
    require('../assets/images/Chayi_turkey_rice_restarunt/夯仔內火雞肉飯/IMG_8430.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/夯仔內火雞肉飯/IMG_8431.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/夯仔內火雞肉飯/IMG_8432.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/夯仔內火雞肉飯/IMG_8433.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/夯仔內火雞肉飯/IMG_8434.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/夯仔內火雞肉飯/IMG_8435.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/夯仔內火雞肉飯/IMG_8436.jpg'),
  ],
  "姐妹": [
    require('../assets/images/Chayi_turkey_rice_restarunt/姐妹/IMG_7636.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/姐妹/IMG_7637.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/姐妹/IMG_7638.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/姐妹/IMG_7639.jpg'),
  ],
  "文化": [
    require('../assets/images/Chayi_turkey_rice_restarunt/文化/IMG_7692.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/文化/IMG_7693.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/文化/IMG_7694.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/文化/IMG_7695.jpg'),
  ],
  "曾家-後庄": [
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9039.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9040.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9041.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9042.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9043.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9044.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9045.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9067.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9068.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9069.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9070.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9071.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9072.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/曾家-後庄/IMG_9073.jpg'),
  ],
  "東門-和平": [
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-和平/IMG_8424.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-和平/IMG_8425.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-和平/IMG_8426.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-和平/IMG_8427.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-和平/IMG_8428.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-和平/IMG_8429.jpg'),
  ],
  "東門-新民": [
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9013(1).jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9013.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9014.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9015.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9016.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9017.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9018.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9019.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9020.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9084.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9085.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9087.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/東門-新民/IMG_9090.jpg'),
  ],
  "桃城三禾": [
    require('../assets/images/Chayi_turkey_rice_restarunt/桃城三禾/IMG_9098.jpg'),
  ],
  "檜町": [
    require('../assets/images/Chayi_turkey_rice_restarunt/檜町/IMG_7658.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/檜町/IMG_7659.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/檜町/IMG_7660.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/檜町/IMG_7661.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/檜町/IMG_7662.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/檜町/IMG_7663.jpg'),
  ],
  "正統": [
    require('../assets/images/Chayi_turkey_rice_restarunt/正統/IMG_7679.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/正統/IMG_7680.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/正統/IMG_7681.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/正統/IMG_7709.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/正統/IMG_7710.jpg'),
  ],
  "民主": [
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8685.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8694.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8695.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8696.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8697.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8701.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8703.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8708.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8709.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8711.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8714.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8723.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8727.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8728.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8734.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8739.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8741.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8742.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8743.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8744.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8745(1).jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8745.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8746(1).jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8746.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8747.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8748.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8749(1).jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8749.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8754.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8758.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8759.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8761.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8762.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/民主/IMG_8763.jpg'),
  ],
  "永芳火雞肉飯": [
    require('../assets/images/Chayi_turkey_rice_restarunt/永芳火雞肉飯/IMG_8392.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/永芳火雞肉飯/IMG_8393.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/永芳火雞肉飯/IMG_8394.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/永芳火雞肉飯/IMG_8395.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/永芳火雞肉飯/IMG_8396.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/永芳火雞肉飯/IMG_8397.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/永芳火雞肉飯/IMG_8398.jpg'),
  ],
  "簡單": [
    require('../assets/images/Chayi_turkey_rice_restarunt/簡單/IMG_7675.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/簡單/IMG_7676.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/簡單/IMG_7677.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/簡單/IMG_7678.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/簡單/IMG_7707.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/簡單/IMG_7708.jpg'),
  ],
  "興安": [
    require('../assets/images/Chayi_turkey_rice_restarunt/興安/IMG_9033.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/興安/IMG_9034.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/興安/IMG_9035.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/興安/IMG_9036.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/興安/IMG_9037.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/興安/IMG_9038.jpg'),
  ],
  "車頭": [
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_7752(1).jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_7752(2).jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_7752.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_7753.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_7754.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_7755.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_7756.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_7757.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_7758.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_9047.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_9048.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_9050.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_9052.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_9054.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_9057.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_9450.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_9451.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/車頭/IMG_9452.jpg'),
  ],
  "郭家-中正": [
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-中正/IMG_9043.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-中正/IMG_9044.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-中正/IMG_9045.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-中正/IMG_9046.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-中正/IMG_9047.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-中正/IMG_9048.jpg'),
  ],
  "郭家-大雅": [
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7759.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7760.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7761.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7762.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7763.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7764.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7765.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7767.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7768.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7769.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7770.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7771.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7772.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-大雅/IMG_7773.jpg'),
  ],
  "郭家-文化": [
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-文化/IMG_8333.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-文化/IMG_8334.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-文化/IMG_8335.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-文化/IMG_8336.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-文化/IMG_8337.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/郭家-文化/IMG_8338.jpg'),
  ],
  "阿信美食": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿信美食/IMG_8399.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿信美食/IMG_8400.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿信美食/IMG_8401.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿信美食/IMG_8402.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿信美食/IMG_8403.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿信美食/IMG_8404.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿信美食/IMG_8405.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿信美食/IMG_8406.jpg'),
  ],
  "阿宏師-中埔": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_8895.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_9046.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_9047.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_9059.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_9060.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_9061.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_9062.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_9063.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_9064.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_9065.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-中埔/IMG_9066.jpg'),
  ],
  "阿宏師-光華總店": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-光華總店/IMG_9055.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-光華總店/IMG_9056.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-光華總店/IMG_9057.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-光華總店/IMG_9058.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-光華總店/IMG_9059.jpg'),
  ],
  "阿宏師-宵夜幫": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-宵夜幫/IMG_7653.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-宵夜幫/IMG_7654.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-宵夜幫/IMG_7655.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-宵夜幫/IMG_7656.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-宵夜幫/IMG_7657(1).jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-宵夜幫/IMG_7657(2).jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿宏師-宵夜幫/IMG_7657.jpg'),
  ],
  "阿德": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9467.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9468.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9469.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9470.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9473.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9474.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9475.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9476.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9477.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9478.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿德/IMG_9479.jpg'),
  ],
  "阿惠": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_8896.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_8897.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_8898.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_8899.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_9048.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_9049.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_9050.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_9051.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_9053.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_9054.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_9055.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_9056.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿惠/IMG_9057.jpg'),
  ],
  "阿明": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿明/IMG_9060.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿明/IMG_9061.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿明/IMG_9062.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿明/IMG_9063.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿明/IMG_9064.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿明/IMG_9065.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿明/IMG_9066.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿明/IMG_9068.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿明/IMG_9069.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿明/IMG_9070.jpg'),
  ],
  "阿樓師": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿樓師/IMG_7649.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿樓師/IMG_7650.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿樓師/IMG_7651.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿樓師/IMG_7652.jpg'),
  ],
  "阿溪": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿溪/IMG_9457.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿溪/IMG_9458.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿溪/IMG_9459.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿溪/IMG_9460.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿溪/IMG_9461.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿溪/IMG_9462.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿溪/IMG_9463.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿溪/IMG_9464.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿溪/IMG_9465.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿溪/IMG_9466.jpg'),
  ],
  "阿福": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿福/IMG_9022.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿福/IMG_9023.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿福/IMG_9024.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿福/IMG_9025.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿福/IMG_9026.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿福/IMG_9027.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿福/IMG_9028.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿福/IMG_9029.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿福/IMG_9030.jpg'),
  ],
  "阿霞-創始店": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞-創始店/IMG_9039.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞-創始店/IMG_9040.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞-創始店/IMG_9041.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞-創始店/IMG_9042.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞-創始店/IMG_9044.jpg'),
  ],
  "阿霞火雞肉飯二代店": [
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8380.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8381.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8382.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8383.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8384.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8385.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8386.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8387.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8388.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8389.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8390.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/阿霞火雞肉飯二代店/IMG_8391.jpg'),
  ],
  "陳家": [
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_7645.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_7646.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_7647.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_7648.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_9491.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_9492.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_9493.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_9494.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_9495.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_9496.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陳家/IMG_9497.jpg'),
  ],
  "陽光": [
    require('../assets/images/Chayi_turkey_rice_restarunt/陽光/IMG_7780.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陽光/IMG_7781.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陽光/IMG_7782.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/陽光/IMG_7783.jpg'),
  ],
  "頂軒": [
    require('../assets/images/Chayi_turkey_rice_restarunt/頂軒/IMG_9049.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頂軒/IMG_9050.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頂軒/IMG_9051.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頂軒/IMG_9052.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頂軒/IMG_9053.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頂軒/IMG_9054.jpg'),
  ],
  "頭家火雞肉飯": [
    require('../assets/images/Chayi_turkey_rice_restarunt/頭家火雞肉飯/IMG_8415.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頭家火雞肉飯/IMG_8416.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頭家火雞肉飯/IMG_8417.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頭家火雞肉飯/IMG_8418.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頭家火雞肉飯/IMG_8419.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頭家火雞肉飯/IMG_8420.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頭家火雞肉飯/IMG_8421.jpg'),
    require('../assets/images/Chayi_turkey_rice_restarunt/頭家火雞肉飯/IMG_8422.jpg'),
  ],
};